version: 2
jobs:
  build:
    docker:
      - image: mtlynch/godot
    steps:
      - checkout
      - run:
          name: create build directory
          command: mkdir dist
      - run:
          name: Export HTML5 version
          command: godot --export HTML5 pong/project.godot "dist/index.html"
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
